### PR TITLE
Hacks

### PR DESCRIPTION
**Pull request by manavg005**
## Changes proposed in this Pull Request :
-  `1.` Added Typescript Folder

## Other changes
- Nope

### CODE REVIEW

**Comment by fineanmol** [comment]
Hi @manavg005 , Please add your name to the Contribution.html file. ✨

**Comment by manavg005** [comment]
> Hi @manavg005 , Please add your name to the Contribution.html file. ✨

Added

**Review by manavg005 — COMMENTED** [review]
Added Name also

**Comment by fineanmol** [comment]
Hi @manavg005, Your Pull request has conflicts, please resolve those conflicts and then submit to merge.
[Click here to check steps to resolve](https://github.com/fineanmol/Hacktoberfest2k21#avoid-conflicts-syncing-your-fork)

**Pull request merged**
