### PR TITLE
stats,transitions,heading enhancement

### PR DESCRIPTION
**Pull request by Naman-pokhriyal**
# Problem
- 
# Solution
-

## Changes proposed in this Pull Request :
-  `1. Stats enhanced`
-  `2. Heading hover effect`
-  `3. Transitions on cards and dark toggle transitions`

## Other changes
-

### CODE REVIEW

**Comment by fineanmol** [comment]
Hi @Naman-pokhriyal , Please add your name to the Contribution.html file. ✨

**Comment by Naman-pokhriyal** [comment]
> Hi @Naman-pokhriyal , Please add your name to the Contribution.html file. ✨

I have added my name in the Contributors.html. I can't locate Contribution.html.

**Comment by Naman-pokhriyal** [comment]
@fineanmol the changes I made to Contributors.html haven't been updated. Only contributors.css have been implemented.
Why is that?

**Comment by fineanmol** [comment]
Hi @Naman-pokhriyal , Please rebase the code and make a new pull request.

**Pull request merged**
