### PR TITLE
InsertionSort.py

### PR DESCRIPTION
**Pull request by sarvekash**
Insertion sort is a simple sorting algorithm that works the way we sort playing cards in our hands.

### CODE REVIEW

**Comment by fineanmol** [comment]
Hi @sarvekash  , Please add your name to the Contribution.html file. ✨

**Comment by sarvekash** [comment]
Done Have a Look

**Comment by fineanmol** [comment]
> Done Have a Look

Please share the line number

**Comment by sarvekash** [comment]
Line 559

**Pull request merged**
