### PR TITLE
Create Snake water gun.py

### PR DESCRIPTION
**Pull request by kingketan9**
# Problem
- 
# Solution
-

## Changes proposed in this Pull Request :
-  `1.`
-  `2.`
-  `..`

## Other changes
-

### CODE REVIEW

**Comment by fineanmol** [comment]
Hi @kingketan9  , Please add your name to the Contribution.html file. ✨

**Comment by kingketan9** [comment]
> Hi @kingketan9 , Please add your name to the Contribution.html file. ✨

i have added my name there

**Comment by fineanmol** [comment]
> > Hi @kingketan9 , Please add your name to the Contribution.html file. ✨
> 
> i have added my name there

Please verify again, It's not present in Contribution.html file

**Comment by kingketan9** [comment]
> > > Hi @kingketan9 , Please add your name to the Contribution.html file. ✨
> > 
> > 
> > i have added my name there
> 
> Please verify again, It's not present in Contribution.html file

yea it is check around line 256

**Pull request merged**
