### PR TITLE
Create flappy.py

### PR DESCRIPTION
**Pull request by OmanshArora**

### CODE REVIEW

**Comment by fineanmol** [comment]
Hi @OmanshArora , Please add your name to the Contribution.html file. ✨

**Comment by OmanshArora** [comment]
> Hi @OmanshArora , Please add your name to the Contribution.html file. ✨

Should I do it again?

**Comment by fineanmol** [comment]
> > Hi @OmanshArora , Please add your name to the Contribution.html file. ✨
> 
> Should I do it again?

Hi Omnash, just add your name in Contribution.html file and your repo will be merged after that

**Comment by OmanshArora** [comment]
Done

**Pull request merged**
