### PR TITLE
array Intersection program

### PR DESCRIPTION
**Pull request by Ishaan-10**
# Problem
 Array Intersection DSA program
# Solution
 Used two pointer approach to solve the same

## Changes proposed in this Pull Request :
-  `1.`
-  `2.`
-  `..`

## Other changes
-

### CODE REVIEW

**Comment by rishabhrathore055** [comment]
Hi @Ishaan-10 , Please add your name to the Contribution.html file. ✨

**Comment by Ishaan-10** [comment]
Done

**Comment by Ishaan-10** [comment]
reopen

**Comment by rishabhrathore055** [comment]
@Ishaan-10  Your Github Url is invalid

**Pull request merged**
