### PR TITLE
added a contributor in cotributors.html

### PR DESCRIPTION
**Pull request by RohanTheProgrammer**
## Changes proposed in this Pull Request :
-  `1.` added a contributor in contributors.html

### CODE REVIEW

**Review by RohanTheProgrammer — COMMENTED** [review]
solved conflicts

**Comment by RohanTheProgrammer** [comment]
Can you help me. I am unable to understand whether this will be counted as a contribution in Hacktoberfest or not.

If yes, could you please mark this as 
> hacktoberfest-accepted

If not, please tell me what I have to do.

**Thank  you**

**Comment by fineanmol** [comment]
Hello @RohanTheProgrammer , Your pull request has already been merged. Yes It'll be counted in hacktoberfest, Don't worry

**Comment by RohanTheProgrammer** [comment]
Thank you so much for answering

**Pull request merged**
